# Demo: Vectors and Matrices with NumPy
## INSTRUCTOR SOLUTIONS

This notebook covers everything you need for **Programming Project 2** — creating vectors and matrices, indexing and slicing them, doing elementwise arithmetic, and removing rows/columns. Follow along, run every demo cell, and complete the "Your Turn" exercises before moving on.

None of the examples below use the exact numbers from Programming Project 2 — the goal is to practice the *tools*, not to give away the assignment's answers.


## 1. NumPy Arrays vs. Python Lists

A regular Python list can hold anything, but it doesn't support the kind of "do this math to every element at once" behavior engineers constantly need. NumPy's `array` type does. You'll almost always create one with `np.array()`, passing in a list.

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_list)
print(my_array)
print(type(my_list))
print(type(my_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


The printed output looks similar, but they behave very differently once you start doing math — more on that in Section 4.

## 2. NumPy Math Functions: `sqrt`, `log`, and Trig Functions

Beyond basic arithmetic, NumPy provides all the math functions you'd expect from a scientific calculator — and every one of them works elementwise on arrays automatically, with no loop needed.

In [12]:
print(np.sqrt(25))      # square root
print(np.log(10))       # NATURAL log (base e) -- matches math "ln"
print(np.log10(100))    # base-10 log -- a DIFFERENT function, easy to mix up with np.log
print(np.exp(1))        # e^1
print(np.pi)             # the constant pi, built into NumPy

5.0
2.302585092994046
2.0
2.718281828459045
3.141592653589793


**Common mistake:** `np.log()` is the *natural* log, not base-10. If a formula says "ln," use `np.log()`. If it explicitly says "log base 10" or "$\log_{10}$," use `np.log10()`. Using the wrong one gives a plausible-looking but wrong number — it won't raise an error, so you have to catch it yourself.

### Degrees vs. Radians — Read This Carefully

Python's trig functions (`np.sin`, `np.cos`, `np.tan`) all expect the **angle in radians**, not degrees. If a problem gives you an angle in degrees (look for the ° symbol), you must convert it first with `np.radians()`.

In [13]:
# WRONG: treating 30 as if it were already in radians
print(np.sin(30))

# RIGHT: convert degrees to radians first
print(np.sin(np.radians(30)))

# np.degrees() does the reverse conversion, radians -> degrees
print(np.degrees(np.pi))

-0.9880316240928618
0.49999999999999994
180.0


Notice how different those first two answers are — `np.sin(30)` computes the sine of 30 *radians* (a huge angle, over 4 full rotations), which is a completely different, but still numeric and "valid-looking," answer. This is exactly the kind of silent bug worth double-checking for.

In [14]:
# Squaring the result of a trig function: cos^2(x) means (cos(x))**2
angle_rad = np.pi / 6
print(np.cos(angle_rad)**2)

# NOT the same as cos(x**2) -- squaring the ANGLE first is a different calculation entirely
print(np.cos(angle_rad**2))

0.7500000000000001
0.962654127659229


Math functions also work directly on entire arrays at once, applying elementwise — no loop needed:

In [15]:
values = np.array([1, 4, 9, 16, 25])
print(np.sqrt(values))    # square root of every element at once

degrees_array = np.array([0, 30, 45, 60, 90])
print(np.sin(np.radians(degrees_array)))   # convert the whole array, then take sine of all of it

[1. 2. 3. 4. 5.]
[0.         0.5        0.70710678 0.8660254  1.        ]


### Your Turn

1. Compute $\sqrt{144}$ using `np.sqrt`
2. Compute the natural log of 50 using `np.log` (NOT `np.log10`)
3. Compute $\sin(45°)$ — remember to convert degrees to radians first
4. Compute $\cos^2(30°)$ — convert to radians, take the cosine, then square the result


In [14]:
# Your Turn
# TODO 1: sqrt(144)
print(np.sqrt(144))

# TODO 2: natural log of 50
print(np.log(50))

# TODO 3: sin(45 degrees)
print(np.sin(np.radians(45)))

# TODO 4: cos^2(30 degrees)
print(np.cos(np.radians(30))**2)

12.0
3.912023005428146
0.7071067811865475
0.7500000000000001


## 3. Creating Arrays: `np.arange`, `np.linspace`, `np.ones`

There are three common ways to build an array of numbers without typing every value by hand.

| Function | Use when... | You specify |
|---|---|---|
| `np.arange(start, stop, step)` | You know the **step size** | start, stop (exclusive!), step |
| `np.linspace(start, stop, num)` | You know the **number of points** | start, stop (inclusive), how many points |
| `np.ones(n)` | You want an array of all 1s | how many elements |


In [2]:
# np.arange: numbers from 0 up to (but NOT including) 10, step size 3
print(np.arange(0, 10, 3))

# np.arange also works with a start of your choice
print(np.arange(5, 20, 5))

[0 3 6 9]
[ 5 10 15]


**Careful:** `np.arange`'s `stop` value is *excluded*. `np.arange(0, 10, 3)` stops at 9, not 10, because the next step (12) would be past the stop value.

In [3]:
# np.linspace: exactly 4 evenly spaced points between 0 and 12 (inclusive of BOTH ends)
print(np.linspace(0, 12, 4))

# Compare: np.linspace's stop value IS included, unlike np.arange
print(np.linspace(0, 10, 5))

[ 0.  4.  8. 12.]
[ 0.   2.5  5.   7.5 10. ]


In [4]:
# np.ones: an array of all 1s
print(np.ones(4))

[1. 1. 1. 1.]


### Your Turn

Create three arrays:
1. Using `np.arange`: the numbers 1, 3, 5, 7, 9 (step size 2)
2. Using `np.linspace`: exactly 6 evenly spaced numbers between 0 and 100 (inclusive)
3. Using `np.ones`: an array of seven 1s


In [21]:
# Your Turn
# TODO 1: np.arange version of 1, 3, 5, 7, 9
print(np.arange(1, 10, 2))

# TODO 2: np.linspace version of 6 numbers between 0 and 100
print(np.linspace(0, 100, 6))

# TODO 3: np.ones version of seven 1s
print(np.ones(7))

[1 3 5 7 9]
[  0.  20.  40.  60.  80. 100.]
[1. 1. 1. 1. 1. 1. 1.]


## 4. Indexing 1D Arrays

Just like strings and lists, NumPy arrays are **0-indexed** — the first element is index `0`, not `1`. Negative indices count backward from the end (`-1` is the last element).

In [5]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])    # first element
print(a[2])    # third element
print(a[-1])   # last element
print(a[1:4])  # a SLICE: elements at index 1, 2, 3 (index 4 is NOT included)

10
30
50
[20 30 40]


**Slicing rule to remember:** `a[start:stop]` includes `start` but *excludes* `stop` — the same rule as `np.arange`.

### Your Turn

Given `b = np.array([100, 200, 300, 400, 500, 600])`:
1. Print the 2nd element (remember: 0-indexed!)
2. Print the last element using negative indexing
3. Print a slice containing just the 3rd, 4th, and 5th elements


In [26]:
# Your Turn
b = np.array([100, 200, 300, 400, 500, 600])

# TODO 1: print the 2nd element
print(b[1])

# TODO 2: print the last element (negative indexing)
print(b[-1])

# TODO 3: print a slice of the 3rd, 4th, and 5th elements
print(b[2:5])

200
600
[300 400 500]


## 5. Elementwise Arithmetic

This is where NumPy arrays really diverge from plain lists. Arithmetic on arrays happens **elementwise** — position by position — with no loop required.

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)     # elementwise addition
print(a * b)     # elementwise multiplication (NOT matrix/dot product!)
print(a * 2)     # multiplying by a single number scales every element

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 2  4  6  8 10]


Compare this to what happens with plain Python lists — `*` on lists does something completely different (repetition, like the string `*` from Week 1), and `+` concatenates instead of adding:

In [7]:
list_a = [1, 2, 3]
print(list_a * 2)      # repeats the list -- NOT elementwise multiplication!
print(list_a + [4,5])  # concatenates -- NOT elementwise addition!

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5]


This is exactly why NumPy arrays exist — they give you the math behavior you actually want for vectors.

### Scalar Multiplication: Array times a Single Number

Separate from elementwise array-times-array multiplication, you'll very often multiply an entire array by a single number (a *scalar*) — e.g., converting every value in an array from one unit to another, or scaling every reading by a calibration constant. This is called **scalar multiplication**, and NumPy applies it to every element automatically.

In [16]:
readings = np.array([10, 20, 30, 40])

print(readings * 2)        # every element doubled
print(readings * 0.5)      # every element halved
print(readings / 10)       # scalar division works the same way
print(-1 * readings)       # flips the sign of every element

[20 40 60 80]
[ 5. 10. 15. 20.]
[1. 2. 3. 4.]
[-10 -20 -30 -40]


Scalar multiplication and elementwise (array-times-array) multiplication can be combined in one expression — this is exactly the pattern you'll need for combining a data vector with a single conversion factor, or a data vector with a whole vector of per-element weights, depending on the situation:

In [17]:
data = np.array([2, 4, 6, 8])
weights = np.array([1.0, 0.5, 2.0, 1.5])

print(data * 3)          # scalar multiplication: same factor applied to every element
print(data * weights)    # elementwise multiplication: a DIFFERENT factor per element

[ 6 12 18 24]
[ 2.  2. 12. 12.]


### Your Turn

Given `temps_C = np.array([0, 10, 20, 30, 40])` (temperatures in Celsius):

1. Convert the whole array to Fahrenheit using scalar operations: $F = C \times \frac{9}{5} + 32$ (this needs both a scalar multiplication AND adding a scalar constant to every element)
2. Separately, given `correction = np.array([1.01, 0.98, 1.02, 0.99, 1.00])`, apply this array as an elementwise correction factor to `temps_C` (not the Fahrenheit version) and print the result


In [37]:
# Your Turn
temps_C = np.array([0, 10, 20, 30, 40])

# TODO 1: convert to Fahrenheit using scalar multiplication and addition
temps_F = temps_C * 9/5 + 32
print(temps_F)

# TODO 2: apply the elementwise correction factor to temps_C
correction = np.array([1.01, 0.98, 1.02, 0.99, 1.00])
print(temps_C * correction)

[ 32.  50.  68.  86. 104.]
[ 0.   9.8 20.4 29.7 40. ]


### Your Turn

Given `weights = np.array([2, 4, 6])` and `values = np.array([5, 10, 15])`:
1. Compute and print their elementwise product
2. Compute and print the elementwise product scaled by 0.5 (i.e., multiply every result by 0.5 too)


In [39]:
# Your Turn
weights = np.array([2, 4, 6])
values = np.array([5, 10, 15])

# TODO 1: elementwise product
product = weights * values
print(product)

# TODO 2: elementwise product scaled by 0.5
print(product * 0.5)

[10 40 90]
[ 5. 20. 45.]


## 6. Building 2D Arrays (Matrices)

A 2D array (matrix) is built the same way as a 1D array, just with a list of lists — each inner list is one row. A very common pattern: build each row as its own 1D array first, then stack them together with `np.array([row1, row2, ...])`.

In [8]:
row1 = np.array([1, 2, 3])
row2 = np.array([4, 5, 6])
row3 = np.array([7, 8, 9])

M = np.array([row1, row2, row3])
print(M)
print("Shape:", M.shape)   # (rows, columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


### Your Turn

Build a 3x4 matrix `N` where:
- Row 1 is `np.arange(0, 8, 2)`
- Row 2 is `np.linspace(1, 10, 4)`
- Row 3 is `np.ones(4)`

Print the finished matrix and its shape.


In [43]:
# Your Turn
row1 = np.arange(0, 8, 2)
row2 = np.linspace(1, 10, 4)
row3 = np.ones(4)

N = np.array([row1, row2, row3])
print(N)
print("Shape:", N.shape)

[[ 0.  2.  4.  6.]
 [ 1.  4.  7. 10.]
 [ 1.  1.  1.  1.]]
Shape: (3, 4)


## 7. Indexing and Slicing 2D Arrays

For a 2D array `M`, use `M[row, column]` — separated by a comma, unlike nested Python lists which need two separate sets of brackets. You can slice rows, columns, or both, and you can pick out specific (non-consecutive) rows/columns using a list of indices.

In [9]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(M[1, 2])       # single element: row index 1, column index 2 -> 6
print(M[0:2, :])      # rows 0-1, ALL columns
print(M[:, [0, 2]])   # ALL rows, only columns 0 and 2 (a list of specific indices)

6
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]
 [7 9]]


**Important:** `M[0:2, :]` means "rows 0 through 1" (index 2 excluded, same slicing rule as always), not "rows 0 through 2."

### Your Turn

Using the same matrix `M` above:
1. Print the element in row index 2, column index 1
2. Print rows 1 and 2 (all columns)
3. Print all rows, but only columns 0 and 1


In [48]:
# Your Turn
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# TODO 1: element at row 2, column 1
print(M[2, 1])

# TODO 2: rows 1 and 2, all columns
print(M[1:3, :])

# TODO 3: all rows, columns 0 and 1
print(M[:, 0:2])

8
[[4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


## 8. Removing Rows or Columns: `np.delete`

`np.delete(array, indices, axis=...)` returns a **new** array with the specified row(s) or column(s) removed. `axis=0` means "remove a row," `axis=1` means "remove a column." You can delete a single index or a list of indices at once.

In [10]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.delete(M, 1, axis=0))         # remove row index 1
print(np.delete(M, [0, 2], axis=1))    # remove columns 0 and 2 at once

[[1 2 3]
 [7 8 9]]
[[2]
 [5]
 [8]]


`np.delete` doesn't change `M` itself — it returns a new array. If you want to keep the result, you need to store it in a variable (or overwrite `M`).

In [11]:
print(M)   # unchanged -- np.delete did not modify M in place

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Your Turn

Using a fresh 4x3 matrix:
```python
P = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
```
1. Remove row index 0, storing the result in `P_no_row0`, and print it
2. Starting from the original `P` again, remove column index 1, storing the result in `P_no_col1`, and print it


In [54]:
# Your Turn
P = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# TODO 1: remove row index 0
P_no_row0 = np.delete(P, 0, axis=0)
print(P_no_row0)

# TODO 2: remove column index 1 (from the ORIGINAL P, not the row-removed version)
P_no_col1 = np.delete(P, 1, axis=1)
print(P_no_col1)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


## Wrap-Up: Putting It All Together

Build a 3x4 matrix `Q` where:
- Row 1: `np.arange(1, 9, 2)` truncated/adjusted as needed to have exactly 4 elements — think about what range you actually need
- Row 2: 4 evenly spaced numbers between 10 and 40 using `np.linspace`
- Row 3: an array of four 1s using `np.ones`

Then:
1. Print `Q`
2. Print just row index 1 of `Q`
3. Print `Q` with column index 2 removed


In [56]:
# Wrap-Up Challenge
row1 = np.arange(1, 9, 2)
row2 = np.linspace(10, 40, 4)
row3 = np.ones(4)

Q = np.array([row1, row2, row3])
print(Q)

# TODO: print row index 1
print(Q[1, :])

# TODO: print Q with column index 2 removed
print(np.delete(Q, 2, axis=1))

[[ 1.  3.  5.  7.]
 [10. 20. 30. 40.]
 [ 1.  1.  1.  1.]]
[10. 20. 30. 40.]
[[ 1.  3.  7.]
 [10. 20. 40.]
 [ 1.  1.  1.]]
